### ISSUE TITLE
sw2801 buffering circuit - only first led flickering, other leds are ok

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#319]
Hi,

I followed this guide to make buffering https://github.com/tvdzwan/hyperion/wiki/hardware but on my SW2801 first led is constantly flickering (other LEDs in chain works great without flickering). And when I am changeing colors on color wheel, first LEDs is flickering and sometimes it does not have the same color as other leds. What I found out - when I put my finger on ground wire flickering is not so huge but color is sometimes not the same as other leds (when using color wheel). What could be the problem?

**Comment by gilsport** [comment]
Same here.....
Solved it?!?!

**Comment by pcaffardi** [comment]
I experienced that when i didnt wired together rpi2 and lee strip grounds (if you use separate power supplies you should keep a common voltage referente). I hope this could help.

**Comment by gilsport** [comment]
HI,
Issue solved.... as you said connecting the ground from the led strip to the pi GPIO3 solved the problem (beside i had connection issues with my power supply but that was solved very easly )

also i found in other forums that long CLK and DI wires might cause some problems so i shorten them as well (they are now about 15 cm long from the PI to the led strip)

enjoy

**Comment by pcaffardi** [comment]
Hi! I still have problems with last led. no matter if i configure N or less
leds, the last led of the configured leds number, always flicks. I tried
writing my own SPI code to change leds color and everything works fine. It
seems that Hyperion does not send the end frame correctly. I think that the
problem is the latch delay hardcoded into APA102 hyperion driver (500us of
delay after the SPI transfer functions is called with success). In my test
such value is not enought. By increasing it the last LED is correcly set.

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-07-26 9:38 GMT+02:00 gilsport <notifications@github.com>:

**Comment by gilsport** [comment]
thats wierd..... didnt happen to me.....
how you connected the wires to the PI (using female connectors or directly) ?

**Comment by pcaffardi** [comment]
I connected using a SN74AHCT00N using the 4 NAND logics to create a
3.3V->5V conversion. I also put a capacitor between ground and power.

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-07-27 15:06 GMT+02:00 gilsport <notifications@github.com>:

**Comment by gilsport** [comment]
How much leds you got and how many amp's
You need at least 30MiliAmps per led

**Comment by pcaffardi** [comment]
I have 98 leds. Current code shouldnt work with more than 64 leds. I
patched by myself correctly Hyperion apa102 driver and now it works fine. I
use 2.5mbit rate. I will submit a patch later.

I would like to drive the leds brigthness, too in some way. I will
investigate how api couls bw adapted to do so.
Il 27/lug/2015 07:24 PM, "gilsport" <notifications@github.com> ha scritto:

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
