### ISSUE TITLE
hyperion unable to re-establish connection to tty device

### ISSUE THREAD

**Issue by mrgreywater** [tvdzwan/hyperion#356]
setup: hyperion with screengrabber input and adalight output to arduino (using usb with the /dev/ttyACM0 serial interface)

When plugging out the usb from the arduino, and then plugging it back in, I would expect for hyperion to detect the reconnected device and send data over the interface again. But in fact, you have to manually restart the hyperion service after you connected the device.

It therefore would be nice if hyperion automatically re-established the connection without a restart.

The only workaround there is for now is creating custom udev-rules to force hyperion to restart when plugging in the device.

**Comment by NicoHood** [comment]
This got fixed here:
https://github.com/tvdzwan/hyperion/pull/353

**Comment by mrgreywater** [comment]
It's still not fixed. Unplugging, waiting and replugging still doesn't make it reconnect properly. You have to manually restart hyperiond to work.

**Comment by NicoHood** [comment]
If the serial device name doesnt change this should work. I've tested this under elementary>ubuntu>debian.

If you use it on raspberry pi you should try to recompile the source. Maybe they did not provide a new compiled version and only applied this fix to the source files but not to the binaries.

**Comment by mrgreywater** [comment]
I will try again when I'm home, but I'm pretty sure I actually tried #353 in particular when it wasn't merged and it didn't work for me. But I didn't spend too much time with it, so I could be wrong.

**Comment by mrgreywater** [comment]
i finally found the time to check it, and yes it works when I build hyperion myself. install_hyperion just references a really old version from mar 2015 (on rpi2 at least), which doesn't have this fix yet. See #436
